/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Game_TicTacToeConnector */

#ifndef _Included_Game_TicTacToeConnector
#define _Included_Game_TicTacToeConnector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Game_TicTacToeConnector
 * Method:    getCellValue
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_Game_TicTacToeConnector_getCellValue
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Game_TicTacToeConnector
 * Method:    makeMove
 * Signature: (III)Z
 */
JNIEXPORT jboolean JNICALL Java_Game_TicTacToeConnector_makeMove
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     Game_TicTacToeConnector
 * Method:    checkWin
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Game_TicTacToeConnector_checkWin
  (JNIEnv *, jobject);

/*
 * Class:     Game_TicTacToeConnector
 * Method:    resetBoard
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_Game_TicTacToeConnector_resetBoard
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
